### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by priore** [Asich/AMTumblrHud#3]
Please, include a podspec file.

thanks, very simple and cute HUD.

**Comment by Asich** [comment]
I will do! Thank you! 😊

**Comment by priore** [comment]
Many thanks, but I think it is also necessary to specify _**s.ios.deployment_target = '7.1'**_, because on an iOS 8 project the pod update displays the message

> Specs satisfying the` AMTumblrHud` dependency were found, but they required a higher minimum target deployment.

**Comment by Asich** [comment]
I just updated spec, seems works normal now

**Comment by priore** [comment]
many thanks
